### ISSUE TITLE
Application locked for some countries in Play Store and F-Droid

### ISSUE THREAD

**Issue by soshial** [Flunzmas/seasoncalendar#80]
The country of my Google Play is Russia, but if I live in Germany or am a temporary user, I cannot install or use your app. Please, remove the restriction.

**Comment by Flunzmas** [comment]
Hey there!

Concerning Play Store, you're right: I have limited the access to central Europe as that is the region I can adequately cover with the current data. And I'd really like to keep it that way until at least #54 is resolved and integrated :grin:.

The F-Droid version however should be available to everyone regardless (since I think there is no geographic restriction), and [here](https://github.com/Flunzmas/seasoncalendar/releases) you can find the latest releases directly as an apk.

But I'd gladly open up the app to every place I do get the data for :)
